language: python
python:
  - "2.6"
  - "2.7"
install:
  - "pip install ."
  - "pip install unittest2"
  - "pip install coverage"
  - "pip install coveralls"
script: >
          coverage run --append --branch --source=ipaddress test_ipaddress.py &&
          python setup.py sdist &&
          pip install --upgrade dist/backport_ipaddress-*.tar.gz &&
          cd /tmp && python -m ipaddress
after_success:
  - "coverage report -m"
  - "coveralls"
